import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
  return (
    <>
      <Helmet>
        <title>Privacy Policy | Pikuboo</title>
        <meta name="description" content="Read Pikuboo's Privacy Policy compliant with the DPDP Act 2023. Learn how we collect, use, and protect your personal information." />
      </Helmet>

      <section style={{ padding: '4rem 1rem', backgroundColor: 'var(--bg-main)', minHeight: '80vh' }}>
        <div className="policy-container">
          <div className="policy-content">
            <h1>Privacy Policy</h1>
            <p className="policy-last-updated">Last updated: June 15, 2026</p>
            
            <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
            
            <p>This Privacy Policy is compliant with the <strong>Digital Personal Data Protection Act, 2023 (DPDP Act)</strong> of India and other applicable data protection laws. As a Data Fiduciary, the Company is responsible for ensuring your Personal Data is processed lawfully, fairly, and transparently.</p>
            
            <p>We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
            
            <h2>Interpretation and Definitions</h2>
            
            <h3>Interpretation</h3>
            <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
            
            <h3>Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul>
              <li>
                <p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
              </li>
              <li>
                <p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
              </li>
              <li>
                <p><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to PIKUBOO CARE PRIVATE LIMITED, Door No.35/546 (old2/286), Padinjarechalil Building, Thrikkakara, Ernakulam, Ernakulam, Kerala, India, 682021.</p>
              </li>
              <li>
                <p><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
              </li>
              <li>
                <p><strong>Country</strong> refers to: Kerala, India</p>
              </li>
              <li>
                <p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
              </li>
              <li>
                <p><strong>Personal Data</strong> (or "Personal Information") is any information that relates to an identified or identifiable individual.</p>
                <p>We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.</p>
              </li>
              <li>
                <p><strong>Service</strong> refers to the Website.</p>
              </li>
              <li>
                <p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
              </li>
              <li>
                <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
              </li>
              <li>
                <p><strong>Website</strong> refers to Pikuboo Care, accessible from <a href="https://www.pikuboo.com/" target="_blank" rel="noopener noreferrer">https://www.pikuboo.com/</a></p>
              </li>
              <li>
                <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
              </li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul>
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
            </ul>

            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using the Service.</p>
            <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
            <p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
            <ul>
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
            </ul>
            <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser.</p>
            <p>Where required by law, we use non-essential cookies (such as analytics, advertising, and remarketing cookies) only with Your consent. You can withdraw or change Your consent at any time using Our cookie preferences tool (if available) or through Your browser/device settings. Withdrawing consent does not affect the lawfulness of processing based on consent before its withdrawal.</p>
            <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
            <ul>
              <li>
                <p><strong>Necessary / Essential Cookies</strong></p>
                <p>Type: Session Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</p>
              </li>
              <li>
                <p><strong>Cookies Policy / Notice Acceptance Cookies</strong></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </li>
              <li>
                <p><strong>Functionality Cookies</strong></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies allow Us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</p>
              </li>
            </ul>

            <h4>Analytics</h4>
            <p>We use Google Analytics, a web analytics service provided by Google LLC ("Google"), to help us understand how users interact with our Service. Google Analytics uses cookies and similar tracking technologies to collect and report on user behavior and website usage.</p>
            <p>The data collected by Google Analytics includes information such as your IP address, browser type, pages visited, time spent on pages, and referring URLs. This information is transmitted to and stored by Google on servers which may be located outside India. Google may use this data to evaluate your use of the Service, compile reports on website activity, and provide other analytics-related services.</p>
            <p>Google may also share this data with third parties where required by law or where such parties process the data on Google's behalf. By using our Service, you consent to the processing of your data by Google in the manner and for the purposes described above.</p>
            <p>You may opt out of Google Analytics tracking at any time by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noopener noreferrer">Google Analytics Opt-out Browser Add-on</a>. For more information on how Google handles data, please refer to <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">Google's Privacy Policy</a>.</p>
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of Our Privacy Policy.</p>

            <h3>Legal Basis for Processing Your Personal Data</h3>
            <p>Under the Digital Personal Data Protection Act, 2023 (DPDP Act) and other applicable laws, We process your Personal Data on the following legal bases:</p>
            <ul>
              <li><strong>Consent:</strong> Where you have given clear consent for Us to process your Personal Data for a specific purpose (e.g., marketing emails, analytics cookies).</li>
              <li><strong>Contractual necessity:</strong> Where processing is necessary to perform a contract with you or to take steps at your request before entering into a contract (e.g., processing your order or managing your account).</li>
              <li><strong>Legal obligation:</strong> Where We are required by law to process your data (e.g., tax records, financial compliance).</li>
              <li><strong>Legitimate interests:</strong> Where processing is necessary for Our legitimate business interests (e.g., fraud prevention, service improvement, security), provided these interests are not overridden by your rights.</li>
            </ul>

            <h3>Use of Your Personal Data</h3>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul>
              <li>
                <p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
              </li>
              <li>
                <p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
              </li>
              <li>
                <p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
              </li>
              <li>
                <p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
              </li>
              <li>
                <p><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</p>
              </li>
              <li>
                <p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
              </li>
              <li>
                <p><strong>For business transfers:</strong> We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
              </li>
              <li>
                <p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
              </li>
            </ul>

            <p>We may share Your Personal Data in the following situations:</p>
            <ul>
              <li><strong>With Service Providers:</strong> We may share Your Personal Data with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
              <li><strong>With Affiliates:</strong> We may share Your Personal Data with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
              <li><strong>With business partners:</strong> We may share Your Personal Data with Our business partners to offer You certain products, services or promotions.</li>
              <li><strong>With other users:</strong> If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
              <li><strong>With Your consent</strong>: We may disclose Your Personal Data for any other purpose with Your consent.</li>
            </ul>

            <h3>Email Communications</h3>
            <p>We may send you emails related to your account activity, purchase confirmations, service updates, and security notices. These transactional emails are sent as part of our Service and cannot be opted out of while you maintain an account with us.</p>
            <p>With your consent, we may also send you marketing emails such as newsletters, promotional offers, and updates about our products and services. You may opt in to receive such communications during registration or through your account settings.</p>
            <p>You can unsubscribe from marketing emails at any time by clicking the "Unsubscribe" link included in every marketing email, or by contacting us directly. Opting out of marketing emails will not affect delivery of transactional or account-related communications.</p>
            <p>We use email service providers to manage and deliver our communications. These providers are bound by confidentiality obligations and are not permitted to use your email address for their own marketing purposes.</p>

            <h3>Advertising</h3>
            <p>We may display advertisements on our Service. These ads may be served directly by us or through third-party advertising networks and platforms, including but not limited to Google AdSense and Meta Audience Network.</p>
            <p>Third-party ad networks may use cookies, web beacons, pixel tags, and similar tracking technologies to collect information about your use of our Service and other websites in order to serve you targeted, interest-based advertisements. The information collected by these networks is governed by their own privacy policies, not ours.</p>
            <p>You may opt out of interest-based advertising by visiting:</p>
            <ul>
              <li><a href="https://optout.aboutads.info/" target="_blank" rel="noopener noreferrer">Digital Advertising Alliance (DAA) Opt-Out</a></li>
              <li><a href="https://optout.networkadvertising.org/" target="_blank" rel="noopener noreferrer">Network Advertising Initiative (NAI) Opt-Out</a></li>
              <li>Google Ads Settings: <a href="https://adssettings.google.com/" target="_blank" rel="noopener noreferrer">adssettings.google.com</a></li>
            </ul>
            <p>Please note that opting out of interest-based advertising does not mean you will stop seeing ads; it means the ads shown to you will be less tailored to your interests.</p>

            <h3>Payment Processing</h3>
            <p>Our Service allows you to purchase products or services. All payment transactions are processed through third-party payment processors. We do not store your full payment card details, UPI credentials, net banking information, or other sensitive financial data on our servers.</p>
            <p>Payment processors we may use are compliant with the Payment Card Industry Data Security Standard (PCI-DSS) and applicable financial regulations in India. By making a payment through our Service, your payment data is handled directly and securely by the relevant payment processor under their own terms and privacy policy.</p>
            <p>We may retain non-sensitive transaction information such as your name, billing address, transaction amount, and order history for accounting, tax compliance, fraud prevention, and customer support purposes. Financial records may be retained for up to 8 years as required under applicable Indian tax and financial laws.</p>
            <p>We encourage you to review the privacy policy of any third-party payment service used during your transactions.</p>

            <h3>Retention of Your Personal Data</h3>
            <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if We are required to retain Your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
            <p>Where possible, We apply shorter retention periods and/or reduce identifiability by deleting, aggregating, or anonymizing data. Unless otherwise stated, the retention periods below are maximum periods ("up to") and We may delete or anonymize data sooner when it is no longer needed for the relevant purpose. We apply different retention periods to different categories of Personal Data based on the purpose of processing and legal obligations:</p>
            <ul>
              <li>
                <p>Account Information</p>
                <ul>
                  <li>User Accounts: retained for the duration of your account relationship plus up to 24 months after account closure to handle any post-termination issues or resolve disputes.</li>
                </ul>
              </li>
              <li>
                <p>Customer Support Data</p>
                <ul>
                  <li>Support tickets and correspondence: up to 24 months from the date of ticket closure to resolve follow-up inquiries, track service quality, and defend against potential legal claims</li>
                  <li>Chat transcripts: up to 24 months for quality assurance and staff training purposes.</li>
                </ul>
              </li>
              <li>
                <p>Usage Data</p>
                <ul>
                  <li>Website analytics data (cookies, IP addresses, device identifiers): up to 24 months from the date of collection, which allows us to analyze trends while respecting privacy principles.</li>
                  <li>Server logs (IP addresses, access times): up to 24 months for security monitoring and troubleshooting purposes.</li>
                </ul>
              </li>
            </ul>
            <p>Usage Data is retained in accordance with the retention periods described above, and may be retained longer only where necessary for security, fraud prevention, or legal compliance.</p>
            <p>We may retain Personal Data beyond the periods stated above for different reasons:</p>
            <ul>
              <li>Legal obligation: We are required by law to retain specific data (e.g., financial records for tax authorities).</li>
              <li>Legal claims: Data is necessary to establish, exercise, or defend legal claims.</li>
              <li>Your explicit request: You ask Us to retain specific information.</li>
              <li>Technical limitations: Data exists in backup systems that are scheduled for routine deletion.</li>
            </ul>
            <p>You may request information about how long We will retain Your Personal Data by contacting Us.</p>
            <p>When retention periods expire, We securely delete or anonymize Personal Data according to the following procedures:</p>
            <ul>
              <li>Deletion: Personal Data is removed from Our systems and no longer actively processed.</li>
              <li>Backup retention: Residual copies may remain in encrypted backups for a limited period consistent with our backup retention schedule and are not restored except where necessary for security, disaster recovery, or legal compliance.</li>
              <li>Anonymization: In some cases, We convert Personal Data into anonymous statistical data that cannot be linked back to You. This anonymized data may be retained indefinitely for research and analytics.</li>
            </ul>

            <h3>Transfer of Your Personal Data</h3>
            <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
            <p>Where required by applicable law, We will ensure that international transfers of Your Personal Data are subject to appropriate safeguards and supplementary measures where appropriate. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

            <h3>Delete Your Personal Data</h3>
            <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
            <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
            <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any Personal Data that You have provided to Us.</p>
            <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

            <h3>Disclosure of Your Personal Data</h3>
            
            <h4>Business Transactions</h4>
            <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
            
            <h4>Law enforcement</h4>
            <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            
            <h4>Other legal requirements</h4>
            <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul>
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>

            <h3>Security of Your Personal Data</h3>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            <h2>Your Rights as a Data Principal</h2>
            <p>Under the Digital Personal Data Protection Act, 2023 (DPDP Act) and other applicable laws, you have the following rights regarding your Personal Data:</p>
            <ul>
              <li><strong>Right to Access:</strong> You have the right to obtain a summary of the Personal Data We hold about you and information about how it has been processed.</li>
              <li><strong>Right to Correction and Erasure:</strong> You have the right to request correction of inaccurate or incomplete Personal Data, and to request erasure of your Personal Data where We no longer have a lawful basis to retain it.</li>
              <li><strong>Right to Withdraw Consent:</strong> Where processing is based on your consent, you have the right to withdraw that consent at any time. Withdrawal does not affect the lawfulness of processing carried out before the withdrawal.</li>
              <li><strong>Right to Grievance Redressal:</strong> You have the right to raise a grievance with Us regarding processing of your Personal Data. We will address your grievance within a reasonable timeframe.</li>
              <li><strong>Right to Nominate:</strong> You may nominate another individual to exercise your rights on your behalf in the event of your death or incapacity.</li>
            </ul>
            <p>To exercise any of these rights, please contact Us using the details provided in the Contact Us section below. We may need to verify your identity before processing your request.</p>

            <h2>Children's Privacy</h2>
            <p>Our Service does not address anyone under the age of 16. We do not knowingly collect personally identifiable information from anyone under the age of 16. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 16 without verification of parental consent, We take steps to remove that information from Our servers.</p>
            <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

            <h2>Links to Other Websites</h2>
            <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
            <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

            <h2>Changes to this Privacy Policy</h2>
            <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
            <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
            <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul>
              <li>
                <p>By email: <a href="mailto:connect@pikuboo.com">connect@pikuboo.com</a></p>
              </li>
              <li>
                <p>By visiting this page on our website: <Link to="/contact">https://www.pikuboo.com/contact</Link></p>
              </li>
              <li>
                <p>By phone: <a href="tel:+919778447996">9778447996</a></p>
              </li>
              <li>
                <p>By mail: Door No.35/546 (old2/286), Padinjarechalil Building, Thrikkakara, Ernakulam, Ernakulam, Kerala, India, 682021</p>
              </li>
            </ul>
          </div>
        </div>
      </section>

      <style>{`
        .policy-container {
          max-width: 800px;
          margin: 0 auto;
          padding: 4rem 2.5rem;
          background-color: var(--bg-white);
          border-radius: var(--radius-lg);
          box-shadow: var(--shadow-soft);
          border: 1px solid rgba(0,0,0,0.03);
        }
        .policy-content h1 {
          font-size: 2.6rem;
          margin-bottom: 0.5rem;
          color: var(--text-dark);
          text-align: center;
        }
        .policy-content h2 {
          font-size: 1.6rem;
          margin-top: 2.5rem;
          margin-bottom: 1rem;
          color: var(--text-dark);
          border-bottom: 1px solid rgba(0,0,0,0.05);
          padding-bottom: 0.5rem;
        }
        .policy-content h3 {
          font-size: 1.2rem;
          margin-top: 1.75rem;
          margin-bottom: 0.75rem;
          color: var(--text-dark);
        }
        .policy-content h4 {
          font-size: 1.1rem;
          margin-top: 1.5rem;
          margin-bottom: 0.5rem;
          color: var(--text-dark);
        }
        .policy-content p {
          font-size: 1.05rem;
          line-height: 1.8;
          color: var(--text-body);
          margin-bottom: 1.2rem;
          text-align: left !important;
        }
        .policy-content ul {
          margin-bottom: 1.5rem;
          padding-left: 1.5rem;
          list-style-type: disc;
        }
        .policy-content li {
          font-size: 1.05rem;
          line-height: 1.8;
          color: var(--text-body);
          margin-bottom: 0.5rem;
          text-align: left !important;
        }
        .policy-content li p {
          margin-bottom: 0;
        }
        .policy-content strong {
          color: var(--text-dark);
          font-weight: 600;
        }
        .policy-content a {
          color: var(--primary);
          text-decoration: underline;
          text-underline-offset: 4px;
          font-weight: 500;
          transition: color 0.2s ease;
        }
        .policy-content a:hover {
          color: var(--primary-hover);
        }
        .policy-last-updated {
          color: var(--text-light);
          font-size: 0.95rem;
          margin-bottom: 3rem !important;
          text-align: center !important;
        }
        @media (max-width: 768px) {
          .policy-container {
            padding: 2.5rem 1.25rem;
            border-radius: var(--radius-md);
          }
          .policy-content h1 {
            font-size: 2rem;
          }
          .policy-content h2 {
            font-size: 1.35rem;
          }
        }
      `}</style>
    </>
  );
};

export default PrivacyPolicy;
